# This file contains secrets that will be used when deploying to Streamlit Cloud
# Add your Groq API key here when deploying to Streamlit Cloud
# GROQ_API_KEY = "your_groq_api_key_here"

# Note: In Streamlit Cloud, you should add your actual API key in the Secrets section
# of the app settings, not directly in this file.
